CREATE TABLE EMPLOYER (
    ID INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , BIRTHDATE DATE
    , POSITION_ID INT NOT NULL
    , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (ID)
);

CREATE TABLE POSITION (
    POSITION_ID INT NOT NULL AUTO_INCREMENT
    , NAME VARCHAR(60) NOT NULL
    , BASIC_SALARY INT NOT NULL
    , PRIMARY KEY (POSITION_ID)
);
